import { BookDetail, BookReview, BookDiscussion } from "@/types/bookDetail";

export const mockBookDetails: BookDetail[] = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "A classic American novel about the Jazz Age, following the mysterious Jay Gatsby and his obsession with the beautiful Daisy Buchanan. Set in the summer of 1922, this timeless tale explores themes of wealth, love, and the American Dream.",
    coverImage: "/book-covers/great-gatsby.jpg",
    genres: ["Classic Literature", "Fiction", "American Literature"],
    status: "read",
    rating: 4.2,
    pages: 180,
    isbn: "9780743273565",
    publisher: "Scribner",
    language: "English",
    publicationYear: 1925,
    publicationDate: "1925-04-10",
    averageRating: 4.2,
    ratingsCount: 1250,
    reviewsCount: 89,
    discussionsCount: 23,
    isPublic: true,
    isFavorite: true,
    personalNotes: "A timeless classic about the American Dream. The symbolism of the green light is particularly powerful.",
    readingProgress: 100,
    startedAt: "2024-01-01T00:00:00Z",
    finishedAt: "2024-01-15T00:00:00Z",
    lastReadAt: "2024-01-15T00:00:00Z",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    addedAt: "2024-01-01T00:00:00Z",
    readAt: "2024-01-15T00:00:00Z",
    progress: 100,
    tags: ["classic", "american-literature", "jazz-age"]
  },
  {
    id: "2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A gripping tale of racial injustice and childhood innocence in the American South. Through the eyes of Scout Finch, we witness her father's courageous defense of a black man falsely accused of rape.",
    coverImage: "/book-covers/mockingbird.jpg",
    genres: ["Classic Literature", "Fiction", "Historical Fiction"],
    status: "read",
    rating: 4.5,
    pages: 281,
    isbn: "9780061120084",
    publisher: "J.B. Lippincott & Co.",
    language: "English",
    publicationYear: 1960,
    publicationDate: "1960-07-11",
    averageRating: 4.5,
    ratingsCount: 2100,
    reviewsCount: 156,
    discussionsCount: 34,
    isPublic: true,
    isFavorite: true,
    personalNotes: "Powerful exploration of morality and justice. Atticus Finch remains one of literature's greatest heroes.",
    readingProgress: 100,
    startedAt: "2024-02-01T00:00:00Z",
    finishedAt: "2024-02-20T00:00:00Z",
    lastReadAt: "2024-02-20T00:00:00Z",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-20T00:00:00Z",
    addedAt: "2024-02-01T00:00:00Z",
    readAt: "2024-02-20T00:00:00Z",
    progress: 100,
    tags: ["classic", "american-literature", "social-justice"]
  },
  {
    id: "3",
    title: "1984",
    author: "George Orwell",
    description: "A dystopian social science fiction novel that follows Winston Smith, a low-ranking member of 'the Party' in a world where independent thinking is a crime punishable by death.",
    coverImage: "/book-covers/1984.jpg",
    genres: ["Dystopian Fiction", "Science Fiction", "Political Fiction"],
    status: "currently-reading",
    rating: 4.3,
    pages: 328,
    isbn: "9780451524935",
    publisher: "Signet Classic",
    language: "English",
    publicationYear: 1949,
    publicationDate: "1949-06-08",
    averageRating: 4.3,
    ratingsCount: 1800,
    reviewsCount: 124,
    discussionsCount: 45,
    isPublic: true,
    isFavorite: false,
    personalNotes: "Chilling portrayal of totalitarianism. The concept of 'Big Brother' is more relevant than ever.",
    readingProgress: 65,
    startedAt: "2024-03-01T00:00:00Z",
    lastReadAt: "2024-03-15T00:00:00Z",
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-03-15T00:00:00Z",
    addedAt: "2024-03-01T00:00:00Z",
    progress: 65,
    tags: ["dystopian", "political", "classic"]
  },
  {
    id: "4",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description: "A fantasy novel about the adventures of Bilbo Baggins, a hobbit who embarks on an unexpected journey with a group of dwarves to reclaim their homeland from the dragon Smaug.",
    coverImage: "/book-covers/hobbit.jpg",
    genres: ["Fantasy", "Adventure", "Children's Literature"],
    status: "currently-reading",
    rating: 4.7,
    pages: 310,
    isbn: "9780547928227",
    publisher: "Houghton Mifflin Harcourt",
    language: "English",
    publicationYear: 1937,
    publicationDate: "1937-09-21",
    averageRating: 4.7,
    ratingsCount: 2500,
    reviewsCount: 198,
    discussionsCount: 67,
    isPublic: true,
    isFavorite: true,
    personalNotes: "A delightful adventure that started the Middle-earth legendarium. Perfect blend of adventure and whimsy.",
    readingProgress: 45,
    startedAt: "2024-03-10T00:00:00Z",
    lastReadAt: "2024-03-20T00:00:00Z",
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-03-20T00:00:00Z",
    addedAt: "2024-03-10T00:00:00Z",
    progress: 45,
    tags: ["fantasy", "adventure", "middle-earth"]
  },
  {
    id: "5",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A romantic novel that follows the character development of Elizabeth Bennet, the dynamic protagonist who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.",
    coverImage: "/book-covers/pride-prejudice.jpg",
    genres: ["Romance", "Classic Literature", "Historical Fiction"],
    status: "want-to-read",
    rating: 4.4,
    pages: 432,
    isbn: "9780141439518",
    publisher: "Penguin Classics",
    language: "English",
    publicationYear: 1813,
    publicationDate: "1813-01-28",
    averageRating: 4.4,
    ratingsCount: 1900,
    reviewsCount: 145,
    discussionsCount: 38,
    isPublic: true,
    isFavorite: false,
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-03-15T00:00:00Z",
    addedAt: "2024-03-15T00:00:00Z",
    progress: 0,
    tags: ["romance", "classic", "british-literature"]
  }
];

export const mockBookReviews: BookReview[] = [
  {
    id: "1",
    bookId: "1",
    author: "Sarah Johnson",
    authorId: "user1",
    title: "A masterpiece of American literature",
    content: "The Great Gatsby perfectly captures the essence of the Jazz Age. Fitzgerald's prose is beautiful and the symbolism throughout the novel is masterful. The green light, the eyes of Dr. T.J. Eckleburg, and the valley of ashes all contribute to a haunting portrait of the American Dream gone wrong.",
    rating: 5,
    likes: 23,
    comments: 5,
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
    isVerified: true,
    helpful: 18,
    notHelpful: 2
  },
  {
    id: "2",
    bookId: "1",
    author: "Michael Chen",
    authorId: "user2",
    title: "Overrated but still good",
    content: "While I can appreciate the literary merit of The Great Gatsby, I found it somewhat overrated. The characters are not particularly likable, and the plot is quite simple. However, Fitzgerald's writing style is undeniably beautiful and the themes are still relevant today.",
    rating: 3,
    likes: 8,
    comments: 12,
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-01-25T00:00:00Z",
    isVerified: false,
    helpful: 6,
    notHelpful: 4
  },
  {
    id: "3",
    bookId: "2",
    author: "Emily Rodriguez",
    authorId: "user3",
    title: "Timeless and powerful",
    content: "To Kill a Mockingbird is one of the most important books I've ever read. Harper Lee's portrayal of racial injustice in the American South is both heartbreaking and inspiring. Atticus Finch remains one of literature's greatest moral heroes.",
    rating: 5,
    likes: 31,
    comments: 8,
    createdAt: "2024-02-25T00:00:00Z",
    updatedAt: "2024-02-25T00:00:00Z",
    isVerified: true,
    helpful: 28,
    notHelpful: 1
  },
  {
    id: "4",
    bookId: "3",
    author: "David Kim",
    authorId: "user4",
    title: "Disturbingly prophetic",
    content: "Reading 1984 in 2024 is a chilling experience. Orwell's vision of totalitarianism feels more relevant than ever. The concepts of 'Big Brother,' 'doublethink,' and 'newspeak' are not just literary devices but warnings about the dangers of unchecked power.",
    rating: 5,
    likes: 19,
    comments: 6,
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
    isVerified: true,
    helpful: 16,
    notHelpful: 1
  },
  {
    id: "5",
    bookId: "4",
    author: "Lisa Thompson",
    authorId: "user5",
    title: "A perfect introduction to Middle-earth",
    content: "The Hobbit is a delightful adventure that serves as the perfect introduction to Tolkien's Middle-earth. Bilbo's character development from a comfortable hobbit to a brave adventurer is beautifully written. The story is accessible to all ages while still containing the depth that Tolkien is known for.",
    rating: 5,
    likes: 27,
    comments: 4,
    createdAt: "2024-03-18T00:00:00Z",
    updatedAt: "2024-03-18T00:00:00Z",
    isVerified: true,
    helpful: 24,
    notHelpful: 0
  }
];

export const mockBookDiscussions: BookDiscussion[] = [
  {
    id: "1",
    bookId: "1",
    author: "Alex Morgan",
    authorId: "user6",
    title: "What does the green light symbolize?",
    content: "I've been thinking about the symbolism of the green light in The Great Gatsby. It seems to represent Gatsby's hopes and dreams, particularly his desire to be with Daisy. But I'm curious about other interpretations. What do you think it symbolizes?",
    likes: 15,
    replies: 8,
    views: 142,
    createdAt: "2024-01-22T00:00:00Z",
    updatedAt: "2024-01-22T00:00:00Z",
    isPinned: false,
    tags: ["symbolism", "themes", "analysis"]
  },
  {
    id: "2",
    bookId: "1",
    author: "Rachel Green",
    authorId: "user7",
    title: "Is Gatsby a hero or a villain?",
    content: "This is a question that's been debated for decades. On one hand, Gatsby is a romantic figure who pursues his dreams with determination. On the other hand, he's involved in illegal activities and his obsession with Daisy borders on unhealthy. What are your thoughts?",
    likes: 22,
    replies: 15,
    views: 198,
    createdAt: "2024-01-28T00:00:00Z",
    updatedAt: "2024-01-28T00:00:00Z",
    isPinned: true,
    tags: ["character-analysis", "morality", "debate"]
  },
  {
    id: "3",
    bookId: "2",
    author: "Tom Wilson",
    authorId: "user8",
    title: "The relevance of To Kill a Mockingbird today",
    content: "Given the current social climate, To Kill a Mockingbird feels more relevant than ever. The themes of racial injustice, moral courage, and standing up for what's right are timeless. How do you think the book's message applies to today's world?",
    likes: 18,
    replies: 12,
    views: 167,
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
    isPinned: false,
    tags: ["social-justice", "relevance", "current-events"]
  },
  {
    id: "4",
    bookId: "3",
    author: "Jennifer Lee",
    authorId: "user9",
    title: "1984 vs. Brave New World - which is more accurate?",
    content: "Both Orwell and Huxley predicted different forms of dystopia. Orwell feared a world where books are banned and information is controlled. Huxley feared a world where people are distracted by entertainment. Which vision do you think is more accurate to our current reality?",
    likes: 31,
    replies: 20,
    views: 245,
    createdAt: "2024-03-12T00:00:00Z",
    updatedAt: "2024-03-12T00:00:00Z",
    isPinned: true,
    tags: ["dystopia", "comparison", "prediction"]
  },
  {
    id: "5",
    bookId: "4",
    author: "Peter Jackson",
    authorId: "user10",
    title: "Book vs. Movie adaptation",
    content: "I recently watched the Hobbit movies and was curious about how they compare to the book. The book is much more concise and focused, while the movies added a lot of extra content. Which do you prefer, and why?",
    likes: 14,
    replies: 9,
    views: 123,
    createdAt: "2024-03-20T00:00:00Z",
    updatedAt: "2024-03-20T00:00:00Z",
    isPinned: false,
    tags: ["adaptation", "comparison", "movies"]
  }
];
