flowchart LR
  us[User Service]
  uls[User Library Service]
  bs[Book Service]
  rs[Review Service]
  fs[Forum Service]
  cs[Chat Service]
  as[Admin Service]
  ans[Analytics Service]
  cbs[Chatbot Service]

  uls --> us
  uls --> bs
  rs --> us
  rs --> bs
  fs --> us
  cs --> us
  cs --> fs
  as --> us

  us --> ans
  uls --> ans
  bs --> ans
  rs --> ans
  fs --> ans
  cs --> ans
  as --> ans
  cbs --> ans
