erDiagram
  BOOK {
    objectId _id PK
    string book_id UK
    string title
    string title_without_series
    string description
    string language_code
    float average_rating
    int num_pages
    string isbn13
    string publication_year
    string publisher
    string url
    string image_url
    string work_id
    string_array series
    string_array similar_books
    string_array genres
    datetime createdAt
    datetime updatedAt
  }

  BOOK_AUTHOR {
    string author_id
    string name
    string role
  }

  BOOK ||--o{ BOOK_AUTHOR : embeds
